version: v1
description: Deploy Hipster Shop app onto GKE cluster

steps:
- name: init-workflow
  image: alpine:latest
  input:
    - echo "Initializing workflow - Deploy hipster Shop app onto GKE cluster"
    - echo "This Workflow will perform the following steps:"
    - echo "  1. Provision GKE cluster with Terraform"
    - echo "  2. Creating a 'hipster-shop' namespace on the Kubernetes cluster"
    - echo "  3. Deploying all services and deployments to create the hipster Shop application"
    - echo "  4. Creating the ingress to access the service"
    - echo "This workflow example assumes that you have an ingress controller installed and configured (as does GKE by default)."


- name: create-namespace
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/hipster-shop-ns.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - init-workflow

- name: redis-cart
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/redis-cart.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - create-namespace

- name: redis-cart-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/redis-cart-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - create-namespace  


- name: adservice
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/adservice.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - create-namespace

- name: adservice-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/adservice-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - create-namespace  

- name: cartservice
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/cartservice.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - create-namespace

- name: cartservice-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/cartservice-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - create-namespace  

- name: checkoutservice
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/checkoutservice.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: checkoutservice-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/checkoutservice-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: currencyservice
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/currencyservice.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: currencyservice-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/currencyservice-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: emailservice
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/emailservice.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: emailservice-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/emailservice-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: frontend
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/frontend.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: frontend-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/frontend-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: expose-service
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/frontend-svc-lb.yaml
    namespace: hipster-shop
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
    - frontend-svc

- name: loadgenerator
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/loadgenerator.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - front-end-svc

- name: paymentservice
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/paymentservice.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: paymentservice-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/paymentservice-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: productcatalogservice
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/productcatalogservice.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart-svc

- name: productcatalogservice-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/productcatalogservice-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - productcatalogservice

- name: recommendationservice
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/recommendationservice.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: recommendationservice-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/recommendationservice-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - recommendationservice



- name: shippingservice
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/shippingservice.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - redis-cart

- name: shippingservice-svc
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: hipster-shop/k8s/shippingservice-svc.yaml
    namespace: default
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/ryanycoleman/nebula-workflow-examples.git
  dependsOn:
  - shippingservice  

# - name: slack-notify
#   image: projectnebula/slack-notification:bf8ecb9
#   spec:
#     apitoken:
#       $type: Secret
#       name: slack-token
#     channel: "#nebula-workflows"
#     message: "Successfully deployed hipster Shop demo!"
#   dependsOn:
#   - expose-service