version: v1
description: Nebula Canary Deploy Demo with Istio

steps:
- name: init-workflow
  image: alpine:latest
  input:
    - echo "Initializing workflow - Nebula Canary Deploy Demo with Istio"
- name: deploy-sockshop-demo
  image: projectnebula/kubectl:bf8ecb9
  spec:
    command: apply
    file: canary-deploy/complete-demo.yaml
    namespace: sock-shop
    cluster:
      name: nebula-demo-cluster
      url:
        $type: Secret
        name: url
      cadata:
        $type: Secret
        name: cadata
      token:
        $type: Secret
        name: token
    git:
      name: nebula-workflow-examples
      repository: https://github.com/kenazk/nebula-workflow-examples.git
  dependsOn:
  - init-workflow
- name: slack-notify
  image: projectnebula/slack-notification:bf8ecb9
  spec:
    apitoken:
      $type: Secret
      name: slack-token
    channel: "#nebula-workflows"
    message: "kenazk deployed sockshop demo!"
  dependsOn:
  - deploy-sockshop-demo
